Homework 5. Task 3. Ivanov Aleksei
Sor4nex/spbu_python_sem1 pull request #10
Opened 2023-10-08 20:22 UTC by Sor4nex

Add solution to the 3 task (Queue) of 5 homework

2023-10-29 23:03 UTC, toadharvard requested changes
Я хотел подробно расписать ошибки, но работа очень похожа на другую. Там и смотри
https://github.com/ArtemKushnir/spbu_pyhton_sem1/pull/15

2023-11-02 19:58 UTC, toadharvard requested changes
Типы в Node. Типы в Queue, head, tail -- Optional
pop должен возвращать результат удаления

2023-11-11 17:49 UTC, toadharvard approved these changes

2023-11-27 18:15 UTC, SpirinEgor approved these changes

2023-11-27 18:15 UTC, merged