Homework 5. Task 1. Ivanov Aleksei
Sor4nex/spbu_python_sem1 pull request #13
Opened 2023-10-12 10:34 UTC by Sor4nex

Added realization to the 1 task (binary calculator) of 5 homework

2023-10-28 10:03 UTC, toadharvard approved these changes
Я бы предпочел, чтобы ты использовал списки для представления чисел (потому что работа с ними в разы быстрее голых строк), но тут кажется все хорошо.

2023-10-28 10:09 UTC, toadharvard commented
А еще возможно функция валидации ввода пользователя избыточна и может быть заменена по аналогии с практикой по исключениям и тестированию

2023-11-02 22:04 UTC, toadharvard requested changes
Ну раз решил так, то переделывай функцию, которая парсит инты тоже через exceptions.

2023-11-02 22:04 UTC, toadharvard commented on src/homeworks/practice5/binary_calculator.py
> +def get_encoding_bit_depth(first_decimal: int, second_decimal: int) -> int:
Почему цикл до ста. Магическое число какое-то

2023-11-02 22:11 UTC, toadharvard commented on src/homeworks/practice5/binary_calculator.py
> +def operation_plus_binary(
Это большая страшная функция и все из-за того, что ты строку решил не переделывать в массив.
Лучше было бы в разы замапить твои строки в массивы. Потом сложить как массивы, а затем обратно в строки. И читается лучше, и придумывать add_additional_term не придется

2023-11-12 12:57 UTC, toadharvard approved these changes
operation_plus_binary не приняли бы в ядро линукс, так как вложенность больше 3 это кринж.
В остальном вроде ок

2023-11-27 18:13 UTC, SpirinEgor approved these changes
Страшная функция, согласен
Лучше так не делать, конечно

2023-11-27 18:13 UTC, merged