Homework 5. Task 2. Ivanov Aleksei
Sor4nex/spbu_python_sem1 pull request #14
Opened 2023-10-13 20:50 UTC by Sor4nex

Added solution to the 2 task(floating numbers) or 5 homework

2023-10-28 10:58 UTC, toadharvard requested changes

2023-10-28 10:58 UTC, toadharvard commented on src/homeworks/practice5/floating_numbers.py
> +def validate_user_input() -> float:
Плохой валидатор, вспомни практику последнюю

2023-10-28 10:58 UTC, toadharvard commented on src/homeworks/practice5/floating_numbers.py
> +def decimal_in_exponential_form(input_decimal: float) -> str:
Неверный ответ на тестовом примере: -2.5

2023-11-14 23:47 UTC, Arsene-Baitenov approved these changes

2023-11-14 23:47 UTC, Arsene-Baitenov commented on src/homeworks/practice5/floating_numbers.py
> +def is_float_number(input_str: str) -> float | None:
Функция возвращает True или False

2023-11-14 23:47 UTC, Arsene-Baitenov commented on src/homeworks/practice5/floating_numbers.py
> +            f"{input_decimal_float} in FP32: {decimal_float_to_binary(input_decimal_float)}"
Чем выделяется этот случай? Почему дефолтные значения для него?
Вообще стоило перенести определение параметров формата в функцию `decimal_float_to_binary`

2023-11-15 15:32 UTC, toadharvard approved these changes

2023-11-27 18:15 UTC, SpirinEgor approved these changes

2023-11-27 18:15 UTC, merged