Practice 3. Task 1. Ivanov Aleksei
Sor4nex/spbu_python_sem1 pull request #5
Opened 2023-09-22 11:06 UTC by Sor4nex

Add solution to the 1 task (Дроби) of 3 practice

2023-10-04 18:20 UTC, toadharvard requested changes

2023-10-04 18:20 UTC, toadharvard commented on src/practice/practice3/fractions.py
> +def find_all_prime_fractions(max_divisor: int) -> list:
Лучше указывать более конкретный тип возвращаемого значения: list[tuple[int]]

2023-10-04 18:20 UTC, toadharvard commented on src/practice/practice3/fractions.py
> +def find_greatest_common_divisor(first_number: int, second_number: int) -> int:
https://docs.python.org/3/library/math.html#math.gcd

2023-10-04 18:20 UTC, toadharvard commented on src/practice/practice3/fractions.py
> +def get_max_divisor() -> int:
По названию неочевидно, что ожидается ввод от пользователя, по сигнатуре функции тоже неясно как считается максимальный делитель

2023-10-04 18:20 UTC, toadharvard commented on src/practice/practice3/fractions.py
> +    for fraction in prime_fractions:
Замени на join, иначе вывод занимает непозволительно много времени на больших числах
  Типа такого
 ```print(' ; '.join([f"{numerator}/{denominator}" for numerator, denominator in prime_fractions]))```

2023-10-10 17:39 UTC, SpirinEgor approved these changes

2023-10-12 18:44 UTC, toadharvard approved these changes

2023-10-12 18:44 UTC, merged