Practice 3. Task 2. Ivanov Aleksei
Sor4nex/spbu_python_sem1 pull request #6
Opened 2023-09-22 12:03 UTC by Sor4nex

Add solution to the 2 task (Игра Быки и Коровы) of 3 practice

2023-10-04 18:39 UTC, toadharvard requested changes

2023-10-04 18:39 UTC, toadharvard commented on src/practice/practice3/cows_and_bools.py
> +        for number in permutations(
Просто сгенерируй случайное число от 1000 до 9999. И приведи к строке. Зачем эта жесть с перестановками?

2023-10-04 18:39 UTC, toadharvard commented on src/practice/practice3/cows_and_bools.py
> +    user_number_guess = ""
Пишешь, что это ЧИСЛО пользователя, а устанавливаешь строку.

2023-10-04 18:39 UTC, toadharvard commented on src/practice/practice3/cows_and_bools.py
> +        else:
else не нужен, если перед этим брейкнулся, не увеличивай вложенность без надобности

2023-10-04 18:39 UTC, toadharvard commented on src/practice/practice3/cows_and_bools.py
> +    numbers_options = [
english: number_options

2023-10-04 18:39 UTC, toadharvard commented on src/practice/practice3/cows_and_bools.py
> +            f"Попытка №{user_attempts + 1}. Введите предполагаемое число: "
Нет валидации ввода
```
Попытка №1. Введите предполагаемое число: 23rrggewoigieq2rt823  r984932
Коров: 1, Быков: 0
```

2023-10-04 18:39 UTC, toadharvard commented on src/practice/practice3/cows_and_bools.py
> +        for number in permutations(
А лучше не приводи к строке и сравнивай числа, а не строки

2023-10-04 18:39 UTC, toadharvard commented on src/practice/practice3/cows_and_bools.py
> +            "Выберите одну из опций:\n1. Начать игру\n2. Правилы игры\n9. Выйти\nВаш выбор: ",
Почему для print_game_rules строку ты выносишь в функцию (а лучше бы в глобальную переменную GAME_RULES_MESSAGE), а тут решил захардкодить?

2023-10-04 18:39 UTC, toadharvard commented on src/practice/practice3/cows_and_bools.py
> +    counter_cows_and_bulls = Counter({"cows": 0, "bulls": 0})
Бесполезный каунтер, который неверно используется, хватает 2 переменных (лучше) или дикта

2023-10-04 19:32 UTC, toadharvard commented on src/practice/practice3/cows_and_bools.py
> +            if user_number_guess.index(numeral) == goal_number.index(numeral):
Ты можешь получить индексы с помощью enumarate(user_number_guess)

Сейчас код неоптимален

2023-11-27 18:12 UTC, SpirinEgor approved these changes

2023-12-16 17:39 UTC, toadharvard approved these changes

2023-12-16 17:39 UTC, merged